create table "public"."logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "deleted_at" timestamp with time zone,
    "status" text not null,
    "content" text not null
);


alter table "public"."logs" enable row level security;

create table "public"."places" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "name" text not null,
    "address" text
);


alter table "public"."places" enable row level security;

create table "public"."things" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone default now(),
    "name" text,
    "description" text,
    "image" text,
    "link" text
);


alter table "public"."things" enable row level security;

CREATE UNIQUE INDEX logs_pkey ON public.logs USING btree (id);

CREATE UNIQUE INDEX places_pkey ON public.places USING btree (id);

CREATE UNIQUE INDEX things_pkey ON public.things USING btree (id);

alter table "public"."logs" add constraint "logs_pkey" PRIMARY KEY using index "logs_pkey";

alter table "public"."places" add constraint "places_pkey" PRIMARY KEY using index "places_pkey";

alter table "public"."things" add constraint "things_pkey" PRIMARY KEY using index "things_pkey";


